# Generated by Django 5.0.4 on 2024-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pincode_medicine_pharmacy_pharmacy_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
