# Generated by Django 5.0.4 on 2024-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pincode_latitude_alter_pincode_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pincode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
