# Generated by Django 5.0.4 on 2024-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
