# Generated by Django 5.0.4 on 2024-05-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_doctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
