# Generated by Django 5.0.4 on 2024-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_doctors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
