# Generated by Django 5.0.4 on 2024-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_pharmacy_location_pharmacy_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
